/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LEDpin8.h
**     Project     : Hexiwear_PEx_2_SDKv2
**     Processor   : MK64FN1M0VDC12
**     Component   : SDK_BitIO
**     Version     : Component 01.017, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-11-18, 19:44, # CodeGen: 22
**     Abstract    :
**
**     Settings    :
**          Component name                                 : LEDpin8
**          SDK                                            : KSDK1
**          GPIO Name                                      : GPIOD
**          PORT Name                                      : PORTD
**          Pin Number                                     : 0
**          Pin Symbol                                     : RGB_R
**          Do Pin Muxing                                  : no
**     Contents    :
**         GetDir    - bool LEDpin8_GetDir(void);
**         SetDir    - void LEDpin8_SetDir(bool Dir);
**         SetInput  - void LEDpin8_SetInput(void);
**         SetOutput - void LEDpin8_SetOutput(void);
**         GetVal    - bool LEDpin8_GetVal(void);
**         PutVal    - void LEDpin8_PutVal(bool Val);
**         ClrVal    - void LEDpin8_ClrVal(void);
**         SetVal    - void LEDpin8_SetVal(void);
**         NegVal    - void LEDpin8_NegVal(void);
**         Init      - void LEDpin8_Init(void);
**         Deinit    - void LEDpin8_Deinit(void);
**
**     (c) Copyright Erich Styger, 2016
**     http      : www.mcuoneclipse.com
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     This is a free software and there is NO WARRANTY.
**     No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDpin8.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup LEDpin8_module LEDpin8 module documentation
**  @{
*/         

#ifndef __LEDpin8_H
#define __LEDpin8_H

/* MODULE LEDpin8. */
/* Include inherited beans */
#include "KSDK1.h"

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_NONE
/* Include shared modules, which are used for whole project */
  #include "PE_Types.h"
  #include "PE_Error.h"
  #include "PE_Const.h"
  #include "IO_Map.h"
  #include "Cpu.h"
#endif

#define LEDpin8_DO_PIN_MUXING  0  /* 1: perform pin muxing in Init(), 0: do not do pin muxing */

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_1_3
  #include "fsl_gpio_driver.h"

  /* only GPIOA, GPIOB, GPIOC, GPIOD, GPIOE, GPIOF and GPIOG are currently supported */
  #define LEDpin8_GPIO_IDX GPIOD_IDX   /* GPIOD */
  #define LEDpin8_PinNumber  0u   /* number of pin, type unsigned integer */

  enum LEDpin8_pinNames{
    RGB_R = GPIO_MAKE_PIN(LEDpin8_GPIO_IDX, LEDpin8_PinNumber),
  };

  extern const gpio_output_pin_user_config_t LEDpin8_OutputConfig[];
  extern const gpio_input_pin_user_config_t LEDpin8_InputConfig[];
#endif

void LEDpin8_Init(void);
/*
** ===================================================================
**     Method      :  LEDpin8_Init (component SDK_BitIO)
**     Description :
**         Driver initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_ClrVal(void);
/*
** ===================================================================
**     Method      :  LEDpin8_ClrVal (component SDK_BitIO)
**     Description :
**         Clears the pin value (sets it to a low level)
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_SetVal(void);
/*
** ===================================================================
**     Method      :  LEDpin8_SetVal (component SDK_BitIO)
**     Description :
**         Sets the pin value to a high value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_NegVal(void);
/*
** ===================================================================
**     Method      :  LEDpin8_NegVal (component SDK_BitIO)
**     Description :
**         Toggles/negates the pin value
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_Deinit(void);
/*
** ===================================================================
**     Method      :  LEDpin8_Deinit (component SDK_BitIO)
**     Description :
**         Driver de-initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

bool LEDpin8_GetVal(void);
/*
** ===================================================================
**     Method      :  LEDpin8_GetVal (component SDK_BitIO)
**     Description :
**         Returns the pin value
**     Parameters  : None
**     Returns     :
**         ---             - Returns the value of the pin:
**                           FALSE/logical level '0' or TRUE/logical
**                           level '1'
** ===================================================================
*/

bool LEDpin8_GetDir(void);
/*
** ===================================================================
**     Method      :  LEDpin8_GetDir (component SDK_BitIO)
**     Description :
**         Return the direction of the pin (input/output)
**     Parameters  : None
**     Returns     :
**         ---             - FALSE if port is input, TRUE if port is
**                           output
** ===================================================================
*/

void LEDpin8_SetDir(bool Dir);
/*
** ===================================================================
**     Method      :  LEDpin8_SetDir (component SDK_BitIO)
**     Description :
**         Sets the direction of the pin (input or output)
**     Parameters  :
**         NAME            - DESCRIPTION
**         Dir             - FALSE: input, TRUE: output
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_SetInput(void);
/*
** ===================================================================
**     Method      :  LEDpin8_SetInput (component SDK_BitIO)
**     Description :
**         Sets the pin as input
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_SetOutput(void);
/*
** ===================================================================
**     Method      :  LEDpin8_SetOutput (component SDK_BitIO)
**     Description :
**         Sets the pin as output
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin8_PutVal(bool Val);
/*
** ===================================================================
**     Method      :  LEDpin8_PutVal (component SDK_BitIO)
**     Description :
**         Sets the pin value
**     Parameters  :
**         NAME            - DESCRIPTION
**         Val             - Value to set. FALSE/logical '0' or
**                           TRUE/logical '1'
**     Returns     : Nothing
** ===================================================================
*/

/* END LEDpin8. */

#endif
/* ifndef __LEDpin8_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
