/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LEDpin6.h
**     Project     : Hexiwear_PEx_2_SDKv2
**     Processor   : MK64FN1M0VDC12
**     Component   : SDK_BitIO
**     Version     : Component 01.015, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-11-09, 14:14, # CodeGen: 12
**     Abstract    :
**
**     Settings    :
**          Component name                                 : LEDpin6
**          SDK                                            : KSDK1
**          GPIO Name                                      : GPIOA
**          PORT Name                                      : PORTA
**          Pin Number                                     : 14
**          Pin Symbol                                     : LED_RED3
**     Contents    :
**         GetDir    - bool LEDpin6_GetDir(void);
**         SetDir    - void LEDpin6_SetDir(bool Dir);
**         SetInput  - void LEDpin6_SetInput(void);
**         SetOutput - void LEDpin6_SetOutput(void);
**         GetVal    - bool LEDpin6_GetVal(void);
**         PutVal    - void LEDpin6_PutVal(bool Val);
**         ClrVal    - void LEDpin6_ClrVal(void);
**         SetVal    - void LEDpin6_SetVal(void);
**         NegVal    - void LEDpin6_NegVal(void);
**         Init      - void LEDpin6_Init(void);
**         Deinit    - void LEDpin6_Deinit(void);
**
**     (c) Copyright Erich Styger, 2016
**     http      : www.mcuoneclipse.com
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     This is a free software and there is NO WARRANTY.
**     No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDpin6.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup LEDpin6_module LEDpin6 module documentation
**  @{
*/         

#ifndef __LEDpin6_H
#define __LEDpin6_H

/* MODULE LEDpin6. */
/* Include inherited beans */
#include "KSDK1.h"

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_NONE
/* Include shared modules, which are used for whole project */
  #include "PE_Types.h"
  #include "PE_Error.h"
  #include "PE_Const.h"
  #include "IO_Map.h"
  #include "Cpu.h"
#endif

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_1_3
  #include "fsl_gpio_driver.h"

  /* only GPIOA, GPIOB, GPIOC, GPIOD, GPIOE, GPIOF and GPIOG are currently supported */
  #define LEDpin6_GPIO_IDX GPIOA_IDX   /* GPIOA */
  #define LEDpin6_PinNumber  14u   /* number of pin, type unsigned integer */

  enum LEDpin6_pinNames{
    LED_RED3 = GPIO_MAKE_PIN(LEDpin6_GPIO_IDX, LEDpin6_PinNumber),
  };

  extern const gpio_output_pin_user_config_t LEDpin6_OutputConfig[];
  extern const gpio_input_pin_user_config_t LEDpin6_InputConfig[];
#endif


void LEDpin6_Init(void);
/*
** ===================================================================
**     Method      :  LEDpin6_Init (component SDK_BitIO)
**     Description :
**         Driver initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_ClrVal(void);
/*
** ===================================================================
**     Method      :  LEDpin6_ClrVal (component SDK_BitIO)
**     Description :
**         Clears the pin value (sets it to a low level)
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_SetVal(void);
/*
** ===================================================================
**     Method      :  LEDpin6_SetVal (component SDK_BitIO)
**     Description :
**         Sets the pin value to a high value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_NegVal(void);
/*
** ===================================================================
**     Method      :  LEDpin6_NegVal (component SDK_BitIO)
**     Description :
**         Toggles/negates the pin value
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_Deinit(void);
/*
** ===================================================================
**     Method      :  LEDpin6_Deinit (component SDK_BitIO)
**     Description :
**         Driver de-initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

bool LEDpin6_GetVal(void);
/*
** ===================================================================
**     Method      :  LEDpin6_GetVal (component SDK_BitIO)
**     Description :
**         Returns the pin value
**     Parameters  : None
**     Returns     :
**         ---             - Returns the value of the pin:
**                           FALSE/logical level '0' or TRUE/logical
**                           level '1'
** ===================================================================
*/

bool LEDpin6_GetDir(void);
/*
** ===================================================================
**     Method      :  LEDpin6_GetDir (component SDK_BitIO)
**     Description :
**         Return the direction of the pin (input/output)
**     Parameters  : None
**     Returns     :
**         ---             - FALSE if port is input, TRUE if port is
**                           output
** ===================================================================
*/

void LEDpin6_SetDir(bool Dir);
/*
** ===================================================================
**     Method      :  LEDpin6_SetDir (component SDK_BitIO)
**     Description :
**         Sets the direction of the pin (input or output)
**     Parameters  :
**         NAME            - DESCRIPTION
**         Dir             - FALSE: input, TRUE: output
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_SetInput(void);
/*
** ===================================================================
**     Method      :  LEDpin6_SetInput (component SDK_BitIO)
**     Description :
**         Sets the pin as input
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_SetOutput(void);
/*
** ===================================================================
**     Method      :  LEDpin6_SetOutput (component SDK_BitIO)
**     Description :
**         Sets the pin as output
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDpin6_PutVal(bool Val);
/*
** ===================================================================
**     Method      :  LEDpin6_PutVal (component SDK_BitIO)
**     Description :
**         Sets the pin value
**     Parameters  :
**         NAME            - DESCRIPTION
**         Val             - Value to set. FALSE/logical '0' or
**                           TRUE/logical '1'
**     Returns     : Nothing
** ===================================================================
*/

/* END LEDpin6. */

#endif
/* ifndef __LEDpin6_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
