/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : XF1.h
**     Project     : Hexiwear_PEx_2_SDKv2
**     Processor   : MK64FN1M0VDC12
**     Component   : XFormat
**     Version     : Component 01.015, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-11-09, 18:06, # CodeGen: 14
**     Abstract    :
**
**     Settings    :
**          Component name                                 : XF1
**          SDK                                            : KSDK1
**          Floating Point                                 : no
**     Contents    :
**         xvformat - unsigned XF1_xvformat(void (*outchar)(void *,char), void *arg, const char *...
**         xformat  - unsigned XF1_xformat(void (*outchar)(void *,char), void *arg, const char *...
**         xsprintf - int XF1_xsprintf(char *buf, const char *fmt, ...);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Mario Viara, 2014-2016, https://github.com/MarioViara/xprintfc
**     http      : http://www.mcuoneclipse.com
**     This an open source software implementing a command line shell with Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file XF1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup XF1_module XF1 module documentation
**  @{
*/         

#ifndef __XF1_H
#define __XF1_H

/* MODULE XF1. */
/* Include inherited beans */
#include "KSDK1.h"

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_NONE
/* Include shared modules, which are used for whole project */
  #include "PE_Types.h"
  #include "PE_Error.h"
  #include "PE_Const.h"
  #include "IO_Map.h"
  #include "Cpu.h"
#endif
/**
 * @file        xformatc.c
 *
 * @brief       Printf C implementation.
 *
 * @author      Mario Viara
 *
 * @version     1.04
 *
 * @copyright   Copyright Mario Viara 2014  - License Open Source (LGPL)
 * This is a free software and is opened for education, research and commercial
 * developments under license policy of following terms:
 * - This is a free software and there is NO WARRANTY.
 * - No restriction on use. You can use, modify and redistribute it for personal,
 *   non-profit or commercial product UNDER YOUR RESPONSIBILITY.
 * - Redistributions of source code must retain the above copyright notice.
 *
 */


#include <stdarg.h> /* open argument list support */

#define XF1_XCFG_FORMAT_FLOAT    0 /* enable/disable floating format (component property) */


unsigned XF1_xformat(void (*outchar)(void *,char), void *arg, const char * fmt, ...);
/*
** ===================================================================
**     Method      :  XF1_xformat (component XFormat)
**     Description :
**         Printf() like function using variable arguments
**     Parameters  :
**         NAME            - DESCRIPTION
**         outchar         - Function pointer to output one new
**                           character
**         arg             - Argument for the output function
**         fmt             - Format options for the list of parameters
**         openArgList     - Open argument list
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

unsigned XF1_xvformat(void (*outchar)(void *,char), void *arg, const char * fmt, va_list args);
/*
** ===================================================================
**     Method      :  XF1_xvformat (component XFormat)
**     Description :
**         Printf() like format function
**     Parameters  :
**         NAME            - DESCRIPTION
**         outchar         - Function pointer to the function
**                           to output one char.
**       * arg             - Argument for the output function.
**         fmt             - Format options for the list of parameters.
**         args            - List of parameters
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

int XF1_xsprintf(char *buf, const char *fmt, ...);
/*
** ===================================================================
**     Method      :  XF1_xsprintf (component XFormat)
**     Description :
**         sprintf() like function
**     Parameters  :
**         NAME            - DESCRIPTION
**       * buf             - Pointer to buffer to be written
**       * fmt             - Pointer to formatting string
**         argList         - Open Argument List
**     Returns     :
**         ---             - number of characters written, negative for
**                           error case
** ===================================================================
*/

/* END XF1. */

#endif
/* ifndef __XF1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
